# Generated by Django 5.2.4 on 2025-07-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
